### PR TITLE
Add bash build script

### PR DESCRIPTION
**Pull request by martinmosegaard**
Added a build script which is approximately the
same as the macOS instructions in INSTALL.md and
the .travis.yml CI file.

Tested locally on macOS 10.12.6.

Inspired by https://crascit.com/2016/04/03/scripting-cmake-builds/
Please comment on changes; perhaps it can be used from .travis.yml or I should update the install doc?

### CODE REVIEW

**Comment by Deltafire** [comment]
Sorry for the delay in responding to this!

A few things come to mind:

- The filename is build.sh, yet is specific to OSX. We should either make the script universal or rename it (build_osx.sh for instance).
- If it's specific to OSX, it should exit with an error message if it's not run under OSX.
- The script uses wget, which isn't available on OSX by default. Better to use curl, which is.
- It should check cmake is installed before attempting to use it.
- We need to mention it in the install docs also.

**Comment by martinmosegaard** [comment]
Thanks for the comments, I will try to correct it.

- Regarding the filename, I did try to encapsulate the macOS specific details in an if-statement. But I have not tested it on Linux.
- Regarding wget, I just copied from the CI file `.travis.yml`, but it is a good point about curl.

**Comment by martinmosegaard** [comment]
Updated based on comments.

**Comment by Deltafire** [comment]
Merged in 684de2c096443e1480190878e45c64fc09a4ef5c.

**Pull request closed without merging**
