### PR TITLE
Added some shortcuts to make my performances easier

### PR DESCRIPTION
**Pull request by Claytone**
Hello! 

I'm trying to use MilkyTracker as a music performance tool with a tiny bluetooth keyboard.

However, this means that using a mouse to click buttons on the screen isn't super practical. 

I've added a few shortcuts so far, but plan to possibly add more. Also, there were a few that didn't work on Windows (like Alt-Tab to switch to previous column) so I added alternatives

Tested on Windows 10.

### CODE REVIEW

**Comment by coderofsalvation** [comment]
NICE!
I also created some shortcuts for easy instrument/sample/pattern navigation, they don't seem to conflict with yours.
Can somebody test this for mac?
I will test this on linux.

**Comment by Claytone** [comment]
Tested on Raspbian

**Comment by coderofsalvation** [comment]
For some reason alt plus/minus did not work on my linux, but if it works on raspbian & windows it might have been my windowmanager stealing those keys dunnow.
I like the alt+i (load instrument) a lot, because it allows to easily override instruments (after navigating using ctrl+up/down) while playing.
I've got an upcoming PR which also allows navigating thru samples (ctrl+shift+up/down) which is nice when sculpting/copying samples.

**Comment by coderofsalvation** [comment]
I think this PR now conflicts with the recent ctrl-h addition (to show help).
I can fix this quite easily.

ps. I've tried the ctrl+tab (previous channel) shortcut in the screencapture of https://github.com/milkytracker/MilkyTracker/pull/291 .
However, I was thinking..have you considered using shift+tab instead for (previous channel?).
I'm noticing that my muscle memory expects that, probably since it's a standard shortcut which is used in all spreadsheet software as well.
How about changing it to shift+tab ?

**Comment by coderofsalvation** [comment]
UPDATE:

* I've solved the conflicts
* forget my proposal for shift-tab (as it conflicts with multi-column selections)
* I've added some nice extra

More info see: https://github.com/milkytracker/MilkyTracker/pull/293

I'm closing this PR for now, so lets communicate in the new PR from now on.
Hope you like it.

**Pull request closed without merging**
