### PR TITLE
feat: [raina] Add toggle for advanced drag n drop

### PR DESCRIPTION
**Pull request by peterbart-lmi**
Raina requested a toggle for the advanced drag and drop feature introduced in https://github.com/milkytracker/MilkyTracker/pull/211

@exelotl

### CODE REVIEW

**Comment by coderofsalvation** [comment]
I like this...lets hit the merge button if nobody else objects in upcoming week no?

**Comment by peterbart-lmi** [comment]
> I like this...lets hit the merge button if nobody else objects in upcoming week no?

Did you have a chance to review the code?

**Comment by coderofsalvation** [comment]
I have reviewed it, tested it (works neato while holding shift!).
Will be included in v1.04 milestone

**Comment by peterbart-lmi** [comment]
> I have reviewed it, tested it (works neato while holding shift!).
> Will be included in v1.04 milestone

I believe I can't merge it without approval. Did you approve it?

**Comment by peterbart-lmi** [comment]
> Oh I've actually merged to this release v1.04 candidate https://github.com/milkytracker/MilkyTracker/tree/rc/1.04 (which also has some other PR's in there).
> How about we close this PR after I release (this week)?
Ah, ok, wasn't aware of the pending release. All good then 👍

**Comment by coderofsalvation** [comment]
I'm also writing some docs for this advanced dragndrop.
What I was able to test:

* **cloning** the selection (sortof a stamp feature) when holding shift while dragging the selection

Let me know if I'm missing something.

**Pull request merged**
